id: P23B2EBBE
initial_creation_type: input
source_metadata:
  title: Bengar Jampal Zangpo
  language: en
  description: 'Texts by Bengar Jampal Zangpo (ban sgar ''jam dpal bzang po), the
    famous Kagyü master who was born in the fifteenth century:'
  volume:
    90cb409a22b94966ad76005f09e5de5e:
      title: Invoking the Blessings of the Kagyü Lineage—‘Dorjechang Thungma’
      parent: Lineage Prayers
created_at: '2022-02-28T22:40:17.719160'
last_modified_at: '2022-02-28T22:40:17.719166'
